### ISSUE TITLE
The buffer information never hits 100%

### ISSUE THREAD

**Issue by robertoferraz** [cjlucas/CJAudioPlayer#2]
The music is playing correctly, but the buffer information (bytesDownloaded) is stopping before hitting the expected (bytesExpected).. the gap is really big! I tried to fix, but unfortunately I could not.

**Comment by cjlucas** [comment]
I assume you're taking about the delegate method - (void)audioPlayer:currentItemDidUpdateDownloadProgressWithBytesDownloaded:bytesExpected: ?  Do you have a file uploaded somewhere that I can test?

**Comment by robertoferraz** [comment]
Yes, this is the method I am talking about, sorry, I forgot to mention it, you can use this link:
http://storage-new.newjamendo.com/download/track/380614/mp31/

**Comment by cjlucas** [comment]
The link you provided uses the "chunked" transfer method. This is currently not supported, but it will be in the future.

Thanks for your interest in the project.
